### ISSUE TITLE
Course Management 

### ISSUE THREAD

**Issue by Wikki2000** [Wikki2000/WIS-Grader#9]
## Description 
This will be responsible for sending request to Wis_Grader API base on ajax request from the client side.

## Acceptance Criteria 
- Create a file app/routes/courses.py for this task.
- Must use **requests** in sending request to the API.
- Update the course API and include jwt_required to only accept request from authenticated to user.
- Retrieve access_token from cookie and add it to header when sending request to API.
- The request and Json response from the API documentation, must tally with the request body and response from the request. Feel free to check the documentation again and amend where necessary (Must be observed strictly). 
- Must return exactly the response from API (e.g., `return jsonify(response.json()), response.status_code`. Except status code from API is 200, then append key (status) and value (Success) to the response before sending to the client side.
- The user (lecturer) ID will be retrieved from the access_token using the method `get_jwt_identity()`.
- The routes base on request from client side are:
    - `/courses`: This route handle **GET** and **PUT** request 
    - `/courses/<string: course_id>`: Thiroute handle **PUT** and **DELETE** request 
- Only two functions should be define in this file as follows:
```python 
@app.routes("/course", methods=["POST", "GET"]) 
def get_post_course():
    # code goes here
```
```python
@app.routes("/course/<string:course_id>", methods=["DELETE", "PUT"]) 
def put_del_course(course_id):
    # code goes here
```

**Comment by AnarchyNinetyNine** [comment]
feat(courses): Implement course management and integrate API

- Created `app/routes/courses.py` to handle GET, POST, PUT, DELETE requests related to courses. 6d358a7a4490d141a80d2a72269e5085c0cf1a8b
- Integrated JWT-based authentication, attaching access_token from the cookie to API requests. be1d0115b5c7d2845cdda7cf2c059c01d530529c , 2beedf74aaca1eedce57f4ad33f38c21476595e5 & 640a3170266b5e8db4babeae220361e421d0361a
- Ensured alignment of request/response with API documentation and added error handling. 65640b2b9d74dd024a42506fee5f60451a0c1891
- `/courses`: Handled POST and GET requests. 87c37fb12c3a46c29fdc0757a0fe0faf4e101b7d
- `/courses/<course_id>`: Handled PUT and DELETE requests. f2adc0c14578de25e52bee5fa859ec77a55e8039
- Appended "status: Success" to the response when API status code is 200. b17665f9089f9eb19e4fd88f85b5557516d33ecc & 65640b2b9d74dd024a42506fee5f60451a0c1891
- Updated lecturer_id retrieval using `get_jwt_identity()`. 
- Updated Swagger documentation and reordered imports alphabetically. b7a8a79ac82c5d8672987d49e420d73a37a78774, deb1fdcd6497f2b9720b38c756ed594e3de6309c & b7479249d884df69df760aba53bd853044f4e9a7
- Added and tested bash scripts for course creation, retrieval, deletion, and modification. 6144676efdf5177af9bc3169e6f695fb7458d5d9 & f456f9e3d970e82cdfd63aa41d018a569198e229

Fixes #9
